name: Test build app
on:
  push:
    branches:
    - main
    
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        run: |
          apt update
          apt install curl
          curl --version
        
